//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VyMapsDataCollector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int ID { get; set; }
        public int SectorID { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public string PlaceType { get; set; }
        public string PlaceTypeUrl { get; set; }
        public string Address { get; set; }
        public string Coordinate { get; set; }
        public string CoordinateUrl { get; set; }
        public string What3Words { get; set; }
        public string What3WordsUrl { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Rating { get; set; }
        public string Social { get; set; }
        public string Website { get; set; }
        public string OpeningHours { get; set; }
        public string WhatOtherSay { get; set; }
        public string ImageLinks { get; set; }
        public string MapLink { get; set; }
        public string AboutTheBusiness { get; set; }
        public string Description { get; set; }
    
        public virtual Sector Sector { get; set; }
    }
}
