//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VyMapsDataCollector.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int ID { get; set; }
        public string LastCountryName { get; set; }
        public string LastDistrictName { get; set; }
        public string LastSectorName { get; set; }
        public string LastCompanyName { get; set; }
    }
}
